[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer_runs = 10000
ignored_error_codes = ["unreachable"]
gas_reports = [
    "CreditVaultProtocol"
]
remappings = [
    "src=src/",
    "forge-std/=lib/forge-std/src/",
]


[profile.default.fuzz]
max_test_rejects = 1_000_000
seed = "0xee1d0f7d9556539a9c0e26aed5e63556"
runs = 1000

[profile.default.invariant]
call_override = false # Override unsafe external calls to perform reentrancy checks
depth = 20
runs = 1000


[profile.smt.model_checker]
engine = "chc"
timeout = 100_000
contracts = {"./src/CreditVaultProtocol.sol" = ["CreditVaultProtocol"]}
invariants = ["contract", "reentrancy"]
targets = [
    "assert",
    "constantCondition",
    "divByZero",
    "outOfBounds",
    "overflow",
    "underflow",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config